version: '3.6'

services:
  service:
    depends_on:
      - kafka
    build:
      context: .
      dockerfile: docker/service.dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
    ports:
      - "8080:8080"

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 9999:8080
    links:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:6.1.0
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "59092:59092" # port for connection outside docker env
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:59092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:59092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
