apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-interactor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-interactor
  template:
    metadata:
      labels:
        app: kafka-interactor
    spec:
      containers:
        - name: kafka-interactor
          image: 836395857571.dkr.ecr.us-east-2.amazonaws.com/kafka-interactor:latest
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "2"
              memory: "2512Mi"
            requests:
              cpu: "1"
              memory: "1512Mi"
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "b-1.mymskcluster.glfyog.c7.kafka.us-east-2.amazonaws.com:9094,b-2.mymskcluster.glfyog.c7.kafka.us-east-2.amazonaws.com:9094"
