apiVersion: v1
kind: Service
metadata:
  name: kafka-interactor-service
spec:
  selector:
    app: kafka-interactor
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
